"""added user role

Revision ID: bd9aa065b33d
Revises: 317634e2848d
Create Date: 2026-01-16 11:01:49.927093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9aa065b33d'
down_revision = '317634e2848d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('user_role')

    # ### end Alembic commands ###
